services:
  - type: web
    name: sozoano-site
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: sozoano
      - key: AUTH_SECRET
        generateValue: true
      - key: AUTH_GOOGLE_ID
        sync: false
      - key: AUTH_GOOGLE_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: AUTH_TRUST_HOST
        value: "true"
